threadwork.oauth.google.clientId=599746811527-o0h8daujjdq1bni0d46o6pc6eg9rgr3u.apps.googleusercontent.com
threadwork.oauth.github.clientId=Ov23li4fgu2IXaSwnp27
threadwork.oauth.microsoft.clientId=333122c1-99fe-4d9c-aa9a-2b3f4494ccef
threadwork.oauth.microsoft.tenant=common
