package com.threadwork.compiler.go

import com.threadwork.compiler.api.CompilerOptions
import com.threadwork.compiler.api.CompilerCodeSymbolKind
import com.threadwork.compiler.api.SingleFileLayoutStrategy
import com.threadwork.core.model.LinkInteractionKinds
import com.threadwork.core.model.NodeKind
import com.threadwork.core.model.NodePort
import com.threadwork.core.model.NodeTextSection
import com.threadwork.core.model.PortDirection
import com.threadwork.core.model.TechnologyMetadata
import com.threadwork.core.model.TypeDefinition
import com.threadwork.core.model.TypeFieldDefinition
import com.threadwork.storage.InMemoryDocumentRepository
import com.threadwork.storage.newDocument
import java.nio.file.Files
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class GoCompilerTest {
    @Test
    fun `generates typed double buffered Go network and runner`() {
        val repository = InMemoryDocumentRepository(newDocument("Typed Go"))
        val root = repository.getDocument().rootNodeId
        repository.updateNodeTechnology(root, TechnologyMetadata("go", "go", "go-compiler"))
        repository.updateNodeFileLayoutStrategy(root, SingleFileLayoutStrategy.id)
        val type = repository.createNode(root, "WorkOrder", NodeKind.Type)
        repository.updateNodeTypeDefinition(
            type.id,
            TypeDefinition(
                mutableListOf(
                    TypeFieldDefinition("id", "number"),
                    TypeFieldDefinition("enabled", "boolean"),
                ),
            ),
        )
        val source = repository.createNode(root, "source", NodeKind.Processor)
        val target = repository.createNode(root, "target", NodeKind.Processor)
        repository.addPort(source.id, NodePort("out", "records", PortDirection.Output))
        repository.addPort(target.id, NodePort("in", "records", PortDirection.Input))
        val link = repository.createLink(root, "records", source.id, "records", target.id, "records")
        repository.updateLinkData(link.id, requireNotNull(link.link).copy(typeDefinitionId = type.id.value))

        val result = GoCompiler().compile(repository.getDocument(), CompilerOptions(projectName = "Typed Go"))

        assertTrue(result.success, result.diagnostics.joinToString { it.message })
        val project = assertNotNull(result.generatedProject)
        val sourceText = project.files.single { it.path.endsWith(".go") }.content
        assertTrue(sourceText.trimStart().startsWith("// Code generated by Threadwork's Go compiler"))
        assertTrue(sourceText.contains("package main"))
        assertTrue(sourceText.contains("type WorkOrder struct"))
        assertTrue(sourceText.contains("id float64"))
        assertTrue(sourceText.contains("enabled bool"))
        assertTrue(sourceText.contains("var records1_a_port ThreadworkBuffer"))
        assertTrue(sourceText.contains("var records1_b_port ThreadworkBuffer"))
        assertTrue(sourceText.contains("func transport_records1"))
        assertTrue(sourceText.contains("threadworkRunner.RecordTransit()"))
        assertTrue(sourceText.contains("threadworkRunner.InstallShutdownSignalHandlers()"))
        assertTrue(sourceText.contains("threadworkRunner.BeginShutdownDrain(10)"))
        assertFalse(sourceText.contains("if !threadworkRunner.IsRunning()"))

        val intelligence = GoCompiler().codeIntelligence(repository.getDocument(), source)
        assertTrue(intelligence.symbols.any {
            it.name == "threadworkRunner" && it.members.any { member -> member.name == "GetShutdownSignal()" }
        })
        assertTrue(intelligence.symbols.any {
            it.name == "records" && it.members.any { member -> member.name == "push(records, item)" }
        })
        assertGoBuilds(sourceText)
    }

    @Test
    fun `provides Go function headers and generated child symbols`() {
        val repository = InMemoryDocumentRepository(newDocument("Go signatures"))
        val root = repository.getDocument().rootNodeId
        repository.updateNodeTechnology(root, TechnologyMetadata("go", "go", "go-compiler"))
        val worker = repository.createNode(root, "work_item", NodeKind.Processor)

        val compiler = GoCompiler()

        assertTrue(
            compiler.generatedFunctionHeader(repository.getDocument(), worker, NodeTextSection.Declaration)
                .startsWith("func run_work_item_"),
        )
        assertEquals(
            setOf(CompilerCodeSymbolKind.GeneratedFunction),
            compiler.generatedEntitySymbols(repository.getDocument(), worker).map { it.kind }.toSet(),
        )
        assertEquals(2, compiler.generatedEntitySymbols(repository.getDocument(), worker).size)
    }

    @Test
    fun `source capability intelligence uses generated Go method spelling`() {
        val repository = InMemoryDocumentRepository(newDocument("Go source capability"))
        val root = repository.getDocument().rootNodeId
        repository.updateNodeTechnology(root, TechnologyMetadata("go", "go", "go-compiler"))
        val provider = repository.createNode(root, "template", NodeKind.Processor)
        val consumer = repository.createNode(root, "consumer", NodeKind.Processor)
        repository.addPort(provider.id, NodePort("source", "source", PortDirection.Output))
        repository.addPort(consumer.id, NodePort("source", "source", PortDirection.Input))
        val link = repository.createLink(root, "page_source", provider.id, "source", consumer.id, "source")
        repository.updateLinkData(
            link.id,
            requireNotNull(link.link).copy(interactionKind = LinkInteractionKinds.Source),
        )

        val intelligence = GoCompiler().codeIntelligence(repository.getDocument(), consumer)

        assertTrue(intelligence.symbols.any { symbol ->
            symbol.name == "page_source" && symbol.members.any { it.name == "page_source.GetSource(parameters)" }
        })
    }

    @Test
    fun `applies composite single file overrides`() {
        val repository = InMemoryDocumentRepository(newDocument("Go override"))
        val root = repository.getDocument().rootNodeId
        repository.updateNodeTechnology(root, TechnologyMetadata("go", "go", "go-compiler"))
        repository.updateNodeFileLayoutStrategy(root, SingleFileLayoutStrategy.id)
        repository.createNode(root, "worker", NodeKind.Processor)
        val override = repository.createNode(root, "@CompositeSingleFile", NodeKind.Processor)
        repository.updateNodeText(
            override.id,
            override.text.copy(
                declaration = "// custom Go assembly\npackage main\n\n{{ runtimeSupport }}\n{{ inlineChildDeclarations }}\n{{ ownDeclaration }}",
            ),
        )

        val result = GoCompiler().compile(repository.getDocument())

        assertTrue(result.success, result.diagnostics.joinToString { it.message })
        assertTrue(assertNotNull(result.generatedProject).files.any { it.content.contains("custom Go assembly") })
    }

    @Test
    fun `ships a continuous runner override template`() {
        assertNotNull(javaClass.getResource("/compiler-templates/go/assembly-single-loop.peb"))
    }

    private fun assertGoBuilds(source: String) {
        val goAvailable = runCatching {
            ProcessBuilder("go", "version").redirectErrorStream(true).start().let { process ->
                process.inputStream.bufferedReader().use { it.readText() }
                process.waitFor() == 0
            }
        }.getOrDefault(false)
        if (!goAvailable) return

        val directory = createTempDirectory("threadwork-go-compiler-")
        val sourceFile = directory.resolve("main.go")
        Files.writeString(sourceFile, source)
        val process = ProcessBuilder("go", "build", "-o", directory.resolve("app").toString(), sourceFile.toString())
            .redirectErrorStream(true)
            .start()
        val output = process.inputStream.bufferedReader().use { it.readText() }
        assertEquals(0, process.waitFor(), output)
    }
}
