fileExtension=go
defaultLayoutStrategyId=single-file
emitLinkFiles=false
staticFiles=
skipCompilerTemplates=true

template.node.declaration=processor.peb
template.processor.declaration=processor.peb
template.generator.declaration=generator.peb
template.service-library.declaration=service-library-declaration.peb
template.group.declaration=composite.peb
template.composite.declaration=composite.peb
template.link.declaration=link-declaration.peb
template.link.instantiation=link-instantiation.peb
template.type.declaration=type-declaration.peb
template.note.declaration=note.peb
template.runtime.support=runtime.peb
template.composite.single-file=assembly-single.peb
